# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v5
      - name: Debug paths
        run: |
         pwd
         ls -a
      - name: Make Check
        run: make check
        
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v5
      - name: Make Test
        run: |
          mkdir -p _build/junit
          make test

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: _build/junit/unit.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: _build/unit-cover.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '50 80'

      #TODO, for microservice intergrations and deployment,
      # needs docker image maintanace and to publish 

        